services:
  routr:
    image: fonoster/routr-one:latest
    env_file: ./voice.env
    ports:
      - 51907:51907
      - 51908:51908
      - 5060:5060/udp
      - 5061:5061/tcp
    restart: unless-stopped
